[[word_count]]
month = 7
year = 2025
fanfiction = 600
novel = 0

[[word_count]]
month = 8
year = 2025
fanfiction = 5200
novel = 0

[[word_count]]
month = 9
year = 2025
fanfiction = 5200
novel = 1000

[[word_count]]
month = 10
year = 2025
fanfiction = 8700
novel = 9000

[[word_count]]
month = 1
year = 2026
fanfiction = 12612
novel = 0

[[word_count]]
month = 2
year = 2026
fanfiction = 12326
novel = 400

[[word_count]]
month = 3
year = 2026
fanfiction = 10000
novel = 0