[[word_count]]
date = "2025-07-04"
fanfiction = 104
novel = 220

[[word_count]]
date = "2025-07-05"
fanfiction = 150
novel = 180

[[word_count]]
date = "2025-08-06"
fanfiction = 130
novel = 210

[[word_count]]
date = "2025-08-07"
fanfiction = 170
novel = 240

[[word_count]]
date = "2025-08-08"
fanfiction = 120
novel = 200
