[[word_count]]
month = 7
year = 2025
fanfiction = 104
novel = 220

[[word_count]]
month = 7
year = 2025
fanfiction = 150
novel = 180

[[word_count]]
month = 7
year = 2025
fanfiction = 130
novel = 210

[[word_count]]
month = 7
year = 2025
fanfiction = 170
novel = 240

[[word_count]]
month = 7
year = 2025
fanfiction = 120
novel = 200
